### PR TITLE
#175 Make fan-out scenario more reliable by using `tryEmitNext`

### PR DESCRIPTION
**Pull request by amrynsky**
Use `tryEmitNext` and handle the result as suggested in the deprecated `EmitterProcessor`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@amrynsky Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kafka&pullRequestId=176)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-kafka&pullRequestId=176) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@amrynsky Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kafka&pullRequestId=176)!

**Comment by amrynsky** [comment]
fix for #175

**Comment by bsideup** [comment]
Hi @amrynsky!

Thanks for the PR!
Despite it being a valid change, I just noticed that the Sinks API usage can be simplified with `Flux#publish`: https://github.com/reactor/reactor-kafka/pull/177

I will close this PR but I appreciate the effort you put into it 👍

**Comment by amrynsky** [comment]
@bsideup as a next step was thinking about trying `ConnectableFlux`  but you was too fast 👍.  Ability to use hot flux for receiver is a great improvement comparing to v 1.2. 
Any other issues I could take to contribute?

**Comment by bsideup** [comment]
@amrynsky actually, I think the same approach can be used with 1.2.x as well :) 

regarding the issues - first of all, thanks for volunteering! The scope of 1.3.0 was to rework the internals (without touching the API), and it is considered done, so there isn't much else to do, but giving it a try and testing various edge cases would help a lot!

**Comment by amrynsky** [comment]
As far as I see attempt to convert KafkaReciever to a hot flux causes 
```
java.lang.IllegalStateException: Multiple subscribers are not supported for KafkaReceiver flux
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.start(DefaultKafkaReceiver.java:308) ~[reactor-kafka-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$createConsumerFlux$10(DefaultKafkaReceiver.java:263) ~[reactor-kafka-1.2.2.RELEASE.jar:1.2.2.RELEASE]
```

because of https://github.com/reactor/reactor-kafka/blob/2e96f8e3a621c7675d33af63015624b81830fbb0/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L245-L249

**Pull request closed without merging**
